#!/usr/bin/env bash
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROMPTS_DIR="${SCRIPT_DIR}/../init/prompts"
OUTPUT_FILE="${SCRIPT_DIR}/../init/seed.sql"
TEMP_FILE="${OUTPUT_FILE}.tmp"

echo -e "${YELLOW}Building seed.sql from prompts...${NC}"

# Проверка существования директории с промптами
if [ ! -d "$PROMPTS_DIR" ]; then
    echo -e "${RED}Error: Prompts directory not found: $PROMPTS_DIR${NC}"
    exit 1
fi

# Начало файла
cat > "$TEMP_FILE" << 'EOF'
-- ============================================================
-- Auto-generated from prompts/ directory
-- DO NOT EDIT THIS FILE MANUALLY
-- Edit files in prompts/ and run scripts/build_seed.sh
-- 
-- Generated at: 
EOF

echo "-- $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$TEMP_FILE"
echo "-- ============================================================" >> "$TEMP_FILE"
echo "" >> "$TEMP_FILE"

# Функция для экранирования SQL-строк (Dollar Quoting для безопасности)
escape_sql_dollar_quote() {
    local content="$1"
    local tag="PROMPT_BODY"
    
    # Проверяем, есть ли в тексте уже такой тег
    while echo "$content" | grep -q "\$${tag}\$"; do
        tag="${tag}_${RANDOM}"
    done
    
    echo "\$${tag}\$${content}\$${tag}\$"
}

# Функция для извлечения значения из YAML frontmatter
extract_yaml_value() {
    local file="$1"
    local key="$2"
    
    # Извлекаем значение между --- и ---
    awk -v key="$key" '
        /^---$/ { in_yaml = !in_yaml; next }
        in_yaml && $1 == key":" { 
            sub(/^[^:]+: */, "")
            # Убираем кавычки если есть
            gsub(/^["'\'']|["'\'']$/, "")
            print
            exit
        }
    ' "$file"
}

# Функция для извлечения тела промпта (после YAML frontmatter)
extract_prompt_body() {
    local file="$1"
    
    # Пропускаем YAML frontmatter и возвращаем остальное
    awk '
        BEGIN { yaml_count = 0; in_body = 0 }
        /^---$/ { 
            yaml_count++
            if (yaml_count == 2) { in_body = 1 }
            next
        }
        in_body { print }
    ' "$file"
}

# Счетчик промптов
prompt_count=0

# Обработка каждого промпта в алфавитном порядке
for prompt_file in "$PROMPTS_DIR"/*.md; do
    if [ ! -f "$prompt_file" ]; then
        continue
    fi
    
    filename=$(basename "$prompt_file")
    
    # Проверяем наличие YAML frontmatter
    if ! head -n 1 "$prompt_file" | grep -q "^---$"; then
        echo -e "${YELLOW}Warning: Skipping $filename (no YAML frontmatter)${NC}"
        continue
    fi
    
    # Извлекаем метаданные
    prompt_id=$(extract_yaml_value "$prompt_file" "id")
    prompt_name=$(extract_yaml_value "$prompt_file" "name")
    prompt_desc=$(extract_yaml_value "$prompt_file" "description")
    prompt_stage=$(extract_yaml_value "$prompt_file" "stage")
    prompt_model=$(extract_yaml_value "$prompt_file" "model")
    
    # Проверяем обязательные поля
    if [ -z "$prompt_id" ] || [ -z "$prompt_name" ]; then
        echo -e "${RED}Error: Missing required fields (id, name) in $filename${NC}"
        exit 1
    fi
    
    # Извлекаем тело промпта
    prompt_body=$(extract_prompt_body "$prompt_file")
    
    if [ -z "$prompt_body" ]; then
        echo -e "${RED}Error: Empty prompt body in $filename${NC}"
        exit 1
    fi
    
    # Экранируем тело промпта
    escaped_body=$(escape_sql_dollar_quote "$prompt_body")
    
    # Формируем NULL для пустых значений
    stage_value="NULL"
    [ -n "$prompt_stage" ] && stage_value="'$prompt_stage'"
    
    model_value="NULL"
    [ -n "$prompt_model" ] && model_value="'$prompt_model'"
    
    desc_value="NULL"
    [ -n "$prompt_desc" ] && desc_value="'$prompt_desc'"
    
    # Добавляем в файл
    cat >> "$TEMP_FILE" << EOF
-- ============================================================
-- Prompt: $prompt_name
-- Source: $filename
-- ============================================================
INSERT INTO system_prompts (id, name, description, body, stage, model, is_active, created_at, updated_at)
VALUES (
    '$prompt_id',
    '$prompt_name',
    $desc_value,
    $escaped_body,
    $stage_value,
    $model_value,
    TRUE,
    NOW(),
    NOW()
)
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    stage = EXCLUDED.stage,
    model = EXCLUDED.model,
    body = EXCLUDED.body,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

EOF
    
    prompt_count=$((prompt_count + 1))
    echo -e "${GREEN}✓${NC} Processed: $prompt_name ($filename)"
done

# Проверяем, что обработали хотя бы один промпт
if [ $prompt_count -eq 0 ]; then
    echo -e "${RED}Error: No valid prompts found in $PROMPTS_DIR${NC}"
    rm -f "$TEMP_FILE"
    exit 1
fi

# Заменяем старый файл новым
mv "$TEMP_FILE" "$OUTPUT_FILE"

echo ""
echo -e "${GREEN}✓ Successfully generated seed.sql${NC}"
echo -e "  Processed: ${GREEN}$prompt_count${NC} prompts"
echo -e "  Output: ${YELLOW}$OUTPUT_FILE${NC}"
