apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pbn-generator.fullname" . }}
type: Opaque
stringData:
  {{- range .Values.secretEnv }}
  {{ .name | lower | replace "_" "-" }}: "{{ .value }}"
  {{- end }}
